steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Lint
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "--disable=R,C", "hello.py"]

  # Run unit tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-vv", "--cov=hello", "test_hello.py"]